apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springsecurity-ingress
spec:
  rules:
   - host: springsecurity.com
     http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: springsecurity-svc
            port:
              number: 8080